name: Scrapper pipeline
run-name: Build and release
on:
  push:
    branches:
      - feature/*
      - fix/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - feature/*
      - fix/*
      - hotfix/*
      - release/*
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: |
          pip install build
          python -m build .
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: 'scrapper.whl'
          path: 'dist/scrapper*.whl'
      - id: version_tag
        name: Get version
        run: |
          if [ ${{ github.ref_name }} != main ]; then suffix="-$(git rev-parse --short HEAD)"; fi
          echo "tag=$(cat pyproject.toml | awk -F"=" '/version/ { gsub(/ /, ""); gsub(/"/,""); print $2 }')$suffix" >> $GITHUB_OUTPUT
  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: 'scrapper.whl'
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          release_name: Release ${{ needs.build.outputs.tag }}
          body: |
            Changes in this release:
              - something
              - somewhat

